TA#48326 [ADD] product_packaging_dimension_decimal: allow to add deci…
Numigi/odoo-product-addons pull request #52
Opened 2023-02-27 10:36 UTC by lanto-razafindrabe

…mal value and change measure UOM

2023-02-28 17:10 UTC, majouda requested changes

2023-02-28 17:10 UTC, majouda commented on product_packaging_dimension_decimal/__manifest__.py
> +    'version': "14.0.1",
Mettre 1.0.0 comme version de module tout court.

2023-02-28 17:10 UTC, majouda commented on product_packaging_dimension_decimal/models/product_packaging.py
> +    packaging_length = fields.Float("Length")
Je ne comprend pas pourquoi tu as créé un nouveau champ au lieu de modifier le champs de base 'length' disponible dans l'objet 'product.packaging' du module delivery

2023-02-28 17:10 UTC, majouda commented on product_packaging_dimension_decimal/views/product_packaging.xml
> +            <xpath expr="//div[@name='height']/span/field[@name='length_uom_name']" position="attributes">
Cette ligne génère cette erreur à l'installation du module sur une version vanille d'Odoo, le champs length_uom_name n'est pas disponible sur la vue  'delivery.product_packaging_delivery_form' 

Element '<xpath expr="//div[@name='height']/span/field[@name='length_uom_name']">' cannot be located in parent view

2023-02-28 17:20 UTC, lanto-razafindrabe commented on product_packaging_dimension_decimal/__manifest__.py
> +    'version': "14.0.1",
C'est d'accord

2023-02-28 17:22 UTC, lanto-razafindrabe commented on product_packaging_dimension_decimal/models/product_packaging.py
> +    packaging_length = fields.Float("Length")
J'ai trouvé ce champ comme champ du module natif, je ne l'ai pas créé en fait. Peux-tu m'indiquer où ça se trouve, je ne l'ai pas identifié. Merci

2023-02-28 17:28 UTC, lanto-razafindrabe commented on product_packaging_dimension_decimal/views/product_packaging.xml
> +            <xpath expr="//div[@name='height']/span/field[@name='length_uom_name']" position="attributes">
Je l'ai testé sur une version vanille d'Odoo 14 communautaire. ça a marché. Peux-t- on faire un point ?

2023-03-02 17:10 UTC, majouda requested changes

2023-03-02 17:10 UTC, majouda commented on product_packaging_dimension_decimal/README.rst
> +As an Administrator of Inventory, I go to ``Inventory > Configuration > Delivery Packages``.
Quand je teste sur un odoo Vanille, il faut que l'utilisateur a le droit "Manage Packages" pour voir le menu `Delivery Packages` 

Merci de l'indiquer dans cette phrase.

2023-03-02 17:10 UTC, majouda commented on product_packaging_dimension_decimal/views/product_packaging.xml
> +                <field name="height_uom_id" nolabel="1" style="width:25%%" />
Lors de la sauvegarde du formulaire `Delivery Packages`, on remarque que l'unité de mesure n'est pas aligné avec les champs height, width and length.

2023-03-03 06:55 UTC, lanto-razafindrabe commented on product_packaging_dimension_decimal/views/product_packaging.xml
> +                <field name="height_uom_id" nolabel="1" style="width:25%%" />
Je vais fixer ça. il parait que ça change suivant l'interface (zoom ou taille de police du navigateur)

2023-03-13 14:24 UTC, majouda commented
Moved to stock repository

2023-03-13 14:24 UTC, closed without merging